server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true #只要加了依赖,默认开启
      routes:
        - id: login-service-route #路由的id,没有固定规则但要求唯一,建议配合服务名
          uri: http://localhost:8106 #匹配后提供服务的路由地址
          predicates: #断言,路径相匹配的进行路由
            - Path=/login
#          filters: #过滤器,可以对请求做一些限制
#            - StripPrefix=1 #去掉请求前缀
